/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sopeng_desireflash_DesireLED */

#ifndef _Included_com_sopeng_desireflash_DesireLED
#define _Included_com_sopeng_desireflash_DesireLED
#ifdef __cplusplus
extern "C" {
#endif

#undef MSM_CAMERA_LED_OFF
#define MSM_CAMERA_LED_OFF 0L
#undef MSM_CAMERA_LED_LOW
#define MSM_CAMERA_LED_LOW 1L
#undef MSM_CAMERA_LED_HIGH
#define MSM_CAMERA_LED_HIGH 2L
#undef MSM_CAMERA_LED_LOW_FOR_SNAPSHOT
#define MSM_CAMERA_LED_LOW_FOR_SNAPSHOT 3L

/*
 * Class:     com_sopeng_desireflash_DesireLED
 * Method:    NativeIsSupportCameraLED
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sopeng_desireflash_DesireLED_NativeIsSupportCameraLED
  (JNIEnv *, jobject);

/*
 * Class:     com_sopeng_desireflash_DesireLED
 * Method:    NativeCtrlCameraLED
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sopeng_desireflash_DesireLED_NativeCtrlCameraLED
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sopeng_desireflash_DesireLED
 * Method:    NativeGetSensorName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sopeng_desireflash_DesireLED_NativeGetSensorName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
